source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Swifixture_Example', :exclusive => true do
  pod 'Swifixture', :path => '../'
end

target 'Swifixture_Tests', :exclusive => true do
  pod 'Swifixture', :path => '../'

  pod 'Quick'
  pod 'Nimble'
end
