# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
# cache: cocoapods
podfile: Example/Podfile
before_install:
  - pip install codecov
after_success:
  - codecov
  - slather
  - bash <(curl -s https://codecov.io/bash) -f xml_report/cobertura.xml
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/Swifixture.xcworkspace -scheme Swifixture-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
